### ISSUE TITLE
[Feature request] Include `nomad job inspect`

### ISSUE THREAD

**Issue by anthonysuterag** [Evertras/khan#1]
Hi, thanks for working on this tool! Great work and very handy. 

As one of the use cases, would it be possible to also support `nomad job inspect`? Usually the output that is returned by Nomad CLI is barely readable, so I think having beautiful format of that would be really helpful.

Cheers!

**Comment by Evertras** [comment]
To clarify, this is a big dump of data as it is.  I'm planning on adding a basic `nomad status <job>` equivalent view shortly, is there anything in particular that's useful in `inspect` that should be included?  Or does it need to be everything in `inspect`?

**Comment by Evertras** [comment]
Initial pass done by #14 , let me know if this is a reasonable enough starting place.  Access by going to Jobs and then hit `i`.

**Comment by anthonysuterag** [comment]
Hi, thanks for implementing this! Appreciate it.
Having the capability of seeing job inspect in `yaml` format is really nice.

But it seems some of the fields are trimmed from the inspect, is there particular reason behind it? 🤔 

Because for instance, I would like to see some field related to Vault policy, but could not find it anywhere.
Would it make sense to display the non null fields? 🤔 

Thanks!

**Comment by Evertras** [comment]
The general reason is that each of these is currently manually implemented in an attempt to make it look nicer.  And while it does look nicer, it also runs into the issue of missing fields as described.  I'm working on a more general solution that should show all fields more nicely and not require all these manual bits.

**Comment by Evertras** [comment]
#17 Is a starting point for this.  Let me know if this works for you as a starting point.

**Comment by anthonysuterag** [comment]
Awesome! Looks great! 
Thanks for addressing this.

There is a small glitch with the line wrapping, when the line is too long and also when scrolling with mouse, it's a bit laggy, not sure if it's due to my resolution or what, but overall it's pretty good.

Happy to close this for now! Great work!
