### ISSUE TITLE
[Feature Request] Timestamp column on Jobs table

### ISSUE THREAD

**Issue by anthonysuterag** [Evertras/khan#16]
I think it would be great if we can see timestamp column on the table of Jobs. 

The reason is sometimes there can be enormous amount of jobs showed up and it will be very helpful to easily point out which is the latest job.

Thank you! 🙇

**Comment by Evertras** [comment]
Kind of a dupe of #15 but to clarify, did you mean a different timestamp than the submit?

**Comment by anthonysuterag** [comment]
Ah yeah, missed that one. What I mean is exactly the submit date.
I will close this ticket

**Comment by anthonysuterag** [comment]
Duplicated with https://github.com/Evertras/khan/issues/15
